# Generated by Django 4.2.7 on 2026-03-18 06:04

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_notifications_unsubscribe_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unsubscribe_token',
            field=models.CharField(db_index=True, default=apps.users.models.generate_unsubscribe_token, max_length=64, unique=True),
        ),
    ]
