# Generated by Django 4.2.7 on 2025-12-02 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "waiting_time_minutes",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Minutes before start to open waiting room",
                    ),
                ),
                (
                    "first_reminder_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minutes before start to send first reminder",
                        null=True,
                    ),
                ),
                (
                    "second_reminder_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minutes before start to send second reminder",
                        null=True,
                    ),
                ),
                ("first_reminder_sent", models.BooleanField(default=False)),
                ("second_reminder_sent", models.BooleanField(default=False)),
                ("waiting_email_sent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_waiting", "In Waiting Room"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="activities.activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "events",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("cancelled", "Cancelled"),
                            ("attended", "Attended"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                (
                    "unsubscribe_token",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "db_table": "enrollments",
                "ordering": ["-enrolled_at"],
            },
        ),
    ]
