# Generated by Django 4.2.7 on 2025-12-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["-enrolled_at"], name="enrollments_enrolle_10fea5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["created_at"], name="events_created_9e2206_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["start_datetime", "status"], name="events_start_d_be0f75_idx"
            ),
        ),
    ]
