# Generated by Django 4.2.7 on 2025-12-11 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0003_enrollment_enrollments_enrolle_10fea5_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingRoomParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("ready", "Ready"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("connection_id", models.CharField(blank=True, max_length=255)),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiting_room_entries",
                        to="events.enrollment",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiting_room_participants",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiting_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Waiting Room Participant",
                "verbose_name_plural": "Waiting Room Participants",
                "db_table": "waiting_room_participants",
                "ordering": ["joined_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "status"],
                        name="waiting_roo_event_i_941044_idx",
                    ),
                    models.Index(
                        fields=["user", "event"], name="waiting_roo_user_id_e90e0f_idx"
                    ),
                ],
                "unique_together": {("event", "user")},
            },
        ),
    ]
