# Generated by Django 4.2.7 on 2025-12-02 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="created_by",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["teacher", "admin"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
