# Generated by Django 4.2.7 on 2025-12-09 19:16

import apps.activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityfile",
            name="file",
            field=models.FileField(
                upload_to="activity_files/%Y/%m/%d/",
                validators=[
                    apps.activities.models.validate_file_extension,
                    apps.activities.models.validate_file_size,
                ],
            ),
        ),
    ]
