# Generated by Django 4.2.7 on 2025-12-02 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("meeting_url", models.URLField(max_length=500)),
                (
                    "meeting_provider",
                    models.CharField(
                        choices=[("google_meet", "Google Meet"), ("jitsi", "Jitsi")],
                        default="jitsi",
                        max_length=20,
                    ),
                ),
                (
                    "meeting_id",
                    models.CharField(
                        db_index=True,
                        help_text="Meeting ID from the provider",
                        max_length=255,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
                "db_table": "meetings",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("joined", "Joined"),
                            ("left", "Left"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Participant",
                "verbose_name_plural": "Meeting Participants",
                "db_table": "meeting_participants",
                "ordering": ["joined_at"],
            },
        ),
    ]
