# Generated by Django 4.2.7 on 2025-12-02 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meetings", "0001_initial"),
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="events.event",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingparticipant",
            index=models.Index(
                fields=["meeting", "status"], name="meeting_par_meeting_df9102_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingparticipant",
            index=models.Index(
                fields=["user", "status"], name="meeting_par_user_id_b0f831_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meetingparticipant",
            unique_together={("meeting", "user")},
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["event", "start_time"], name="meetings_event_i_3dc572_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["meeting_id"], name="meetings_meeting_a9a11f_idx"
            ),
        ),
    ]
